kind: pipeline
name: default

steps:
- name: docker
  image: plugins/gcr
  settings:
    repo: principal-iris-230413/bookshelf
    tags:
      - latest
      - "${DRONE_COMMIT}"
    json_key:
      from_secret: google_credentials
  when:
    event: push
